---
title: Life as a Productivity Tool..
author: cube
date: '2021-04-21'
slug: 2021-04-21-life-productivity-tool
categories: []
tags: []
Description: ''
menu: ''
---

## A new tool is spotted in the wild !

I love productivity tools. Correction, I am obsessed with productivity tools. To-Dos, Notes, Planners, all kinds. If there is a tool that was released, I have probably tried it, trying it right now and saving up time and money to do it soon. It's a problem, I am working on it. <--

## The Cycle of (percieved) Improvement

The cycle of testing this tools also always follow the same pattern:

- `Step 1`: Discover a new tool, get crazy exited about all it's features.
- `Step 2`: Bargain with myself that I don't need a new tool, but constantly obsesses over it.
- `Step 3`: Hit a minor roadbloack in my current workflow and find unqualified justification to move tools.
- `Step 4`: Create a dedicated new system to manage all my work and tasks "perfectly" now.
- `Step 5`: Ride the initial rush of trying a newetool and starting the cycle once again.

## Ch-ch-ch-ch-changes !

The big reason I really enjoy going through this cycle over and over again (outside of my love to try new tools) is I hate minor inconveniences, even a small bump in the road really frustrates me. I just blame the tool for not being able to fit my requirements, and end up moving on to the next one without thinking twice about it.

## Extending it to Life..

The trouble comes when I extend the same attitude towards how I treat my life. I pretend that life is also an optimisation problem and I just need to find the best workflow to overcome the challenges and minor inconveniences. But life demands more time and respect, you just can't uproot everything you hate in one instant and start fresh. Things need to be processws, break old shitty habits, heal and then move on. Taking it up at such a fast pace doesn't really eliminate the problems, it just moves them to the background so they don't bother you every day. Still taking their time to process and heal. I hope to accept that some day, until then..

## Recommendation 

Since we are on the topic of tools and you looking for one, I will strongly suggest a non-tool: [**Bullet Journal**](https://bulletjournal.com/). It's is truly life changing. Enjoy!

`Tata !`

`- cube .`